### ISSUE TITLE
Question: Database structure

### ISSUE THREAD

**Issue by thoschworks** [aljazceru/mattermost-retention#1]
Thanks for this nice little tool.

I want to use different time spans for different teams and channels. Do you have information about the database structure?

BTW: I think it should be possible to run the script in an extra container as long as the volumes of the main app are mounted to the additional container.

**Comment by aljazceru** [comment]
@thoschworks you should be able to export database schema with pg_dump or check the table structure with `\dt posts` via psql tool to see how to limit them per team/channel
