### ISSUE TITLE
Can't run script inside Docker

### ISSUE THREAD

**Issue by daurpam** [aljazceru/mattermost-retention#5]
Thank your for the useful script, but unfortunately I can't run it inside the official mattermost docker.

I've tried to run on the APP container that has the mattermost_data path, but inside this container there isn't a "psql" command.
If I try to run on the DB container it hasn't access to the mattermost_data path. 

Both of the containers haven't got the bash shell and I have to use sh, and I don't know if this could be the issue. Commands I've tried:
### 1. From command line using mattermost APP container
`docker exec -ti mattermost_app_1 /mattermost/config/mattermost-retention.sh`
Error message:
> OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "no such file or directory": unknown

### 2. Inside mattermost APP container
``` 
docker exec -ti mattermost_app_1 sh
/mattemost/config/retention.sh
```
Error message: 
> sh: /mattermost/config/retention.sh: not found

### 3. Same both error, using command line & inside the mattermost DB container
`docker exec mattermost_db_1 /var/lib/postgresql/data/mattermost-retention.sh`
Error message:
> date: invalid date '183 day ago'
> Using postgres database.
> ERROR:  syntax error at or near ";"
> LINE 1: select path from fileinfo where createat < ;

Thanks in advance. Regards

**Comment by daurpam** [comment]
Finally I made a workaround using "docker exec" command to execute psql sentences from shell. 

Thanks for the script!

**Comment by aljazceru** [comment]
@daurpam do you mind sharing how exactly you got it to work as it might come in handy for other people as well

**Comment by daurpam** [comment]
@aljazceru Sure! 
NOTE: The messages are deleted from server but clients doesn't refresh that info because the cache.

This is the modified script to run in shell with using **docker exec** command and for **only postgreSQL**:

``` BASH
#!/bin/bash

## configure vars
DB_USER="mmuser"
DB_NAME="mattermost"
#DB_PASS=""
## Name of the docker container with mattermost database
DB_HOST="mattermost-docker_db_1"
RETENTION="180"
## Local directory mapped to the /mattermost/data directory inside docker app container
DATA_PATH="/home/docker/mattermost-docker/volumes/app/mattermost/data/"
TMP_FILE=/tmp/mattermost-paths.list

## calculate epoch in milisec
delete_before=$(date  --date="$RETENTION day ago"  "+%s%3N")
echo $(date  --date="$RETENTION day ago")

## echo "Using postgres database."
#export PGPASSWORD=$DB_PASS

##get list of files to be removed
docker exec -ti $DB_HOST psql -P pager=off -U $DB_USER $DB_NAME -t -c "select path from fileinfo where createat < $delete_before;" > $TMP_FILE
docker exec -ti $DB_HOST psql -P pager=off -U $DB_USER $DB_NAME -t -c "select thumbnailpath from fileinfo where createat < $delete_before;" >> $TMP_FILE
docker exec -ti $DB_HOST psql -P pager=off -U $DB_USER $DB_NAME -t -c "select previewpath from fileinfo where createat < $delete_before;" >> $TMP_FILE

## cleanup db
docker exec -ti $DB_HOST psql -P pager=off -U $DB_USER $DB_NAME -t -c "delete from posts where createat < $delete_before;"
docker exec -ti $DB_HOST psql -P pager=off -U $DB_USER $DB_NAME -t -c "delete from fileinfo where createat < $delete_before;"

## delete files
while read -r fp; do
        if [ -n "$fp" ]; then
                echo "$DATA_PATH""$fp"
                shred -u "$DATA_PATH""$fp"
        fi
done < $TMP_FILE

##cleanup after yourself
## I don't remove this file to have a list of erased files, til re-run script again
#rm /tmp/mattermost-paths.list

#cleanup empty data dirs
find $DATA_PATH -type d -empty -delete
exit 0
```

**Comment by aljazceru** [comment]
thanks @daurpam

**Comment by ados8** [comment]
I have tried all the above and the main script to no avail.
I'm using UNRAID, running out the docker as root:
`/path to script/mattermost-retention.sh` gives permission error.
Running `docker exec mattermost -it sh /path to script/mattermost-retention.sh` gives OCI runtime exec failed regardless of script.

Inside the docker:
`/path to script/mattermost-retention.sh` gives permission error. (also placed script inside the docker with same issue)

I don't know how to get this working 😥

**Comment by daurpam** [comment]
My script working on the shell outside the docker, because is using `docker exec`.
Perhaps you need to run as sudo? or superuser? I don't know about unraid permissions, but perhaps you have to change the onwer of the script or run as other user. Could you post the script that you are using?

Regards

**Comment by ados8** [comment]
> My script working on the shell outside the docker, because is using `docker exec`. Perhaps you need to run as sudo? or superuser? I don't know about unraid permissions, but perhaps you have to change the onwer of the script or run as other user. Could you post the script that you are using?
> 
> Regards

I have tried using the modified docker exec script but same denied issues or other problems
Unraid runs root by default from admin console
I have attached my script
[mattermost-retention.txt](https://github.com/aljazceru/mattermost-retention/files/10121103/mattermost-retention.txt)

**Comment by daurpam** [comment]
@ados8 I don't see any special change in your script. The issue must be related with the unraid permissions users. 
I've suppose that when you save the script as .sh file, you change it to be executable `chmod +x ` and change owner to root if working user is not that `chown root:root`

Perhaps someone with unraid can help you with it.

**Comment by ados8** [comment]
> @ados8 I don't see any special change in your script. The issue must be related with the unraid permissions users. I've suppose that when you save the script as .sh file, you change it to be executable `chmod +x ` and change owner to root if working user is not that `chown root:root`
> 
> Perhaps someone with unraid can help you with it.

Thanks I tried that and now it runs but with container name error.
![image](https://user-images.githubusercontent.com/49982433/206695366-fe7e9f34-71d7-4561-845a-83e23e3fb11e.png)
This is odd because I have triple confirmed its correct name.
![image](https://user-images.githubusercontent.com/49982433/206695510-25d4efde-475e-4a23-90d0-5b35da7a67c7.png)

**Comment by ados8** [comment]
There was issues in the script that wouldn't work for UNRAID.
Modified and working perfectly with appended logging.
