### ISSUE TITLE
Posgresql 15

### ISSUE THREAD

**Issue by Ityumenev** [aljazceru/mattermost-retention#8]
1.I installed mattermost on my server. But there is a minus just with cleaning files in the free version. Will this script work with postgresql -15 version?
2. Do you need to stop SQL or mattermost before using the script?
3. After application, should everything be cleaned immediately? Or does the server need to be restarted?

**Comment by aljazceru** [comment]
Hi,
Haven't tested this with pg15 as i'm not using mattermost anymore, you should run it on a live env - at least sql needs to be working otherwise it can't run
